---
version: "2.1"
services:
        unifi-controller:
                image: linuxserver/unifi-controller
                container_name: unifi
                environment:
                        - PUID=${XUID}
                        - PGID=${XGID}
                        - MEM_LIMIT=1024M #optional
                volumes:
                        - /apps/unifi/config
                ports:
                        - 3478:3478/udp
                        - 10001:10001/udp
                        - 8080:8080
                        - 8081:8081
                        - 8443:8443
                        - 8843:8843
                        - 8880:8880
                        - 6789:6789
                restart: unless-stopped
